[package]
name = "reth-log-index-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Common types for Log index implementation"

[lints]
workspace = true

[dependencies]
# alloy
alloy-primitives.workspace = true

# reth
reth-codecs = { workspace = true, optional = true }

# misc
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true, default-features = false }
sha2 = { workspace = true, default-features = false }
fnv = { workspace = true, default-features = false }

[dev-dependencies]
# For tests
alloy-consensus.workspace = true
rand.workspace = true
test-fuzz.workspace = true
futures.workspace = true

# For integration tests
reth-ethereum-primitives = { workspace = true, features = ["test-utils"] }
reth-storage-errors.workspace = true

[features]
default = []
reth-codec = ["dep:reth-codecs"]
test-utils = [
    "reth-codecs/test-utils",
    "reth-ethereum-primitives/test-utils",
]
